coverage:
  ignore:
    - "builtin"
    - "ast"
    - "ast/fromgo"
    - "ast/togo"
    - "demo"
    - "env"
    - "test"
    - "scanner"
    - "format"
    - "cmd"
    - "cl/cltest"
    - "cl/outline"
    - "cl/internal/spx2"
    - "cl/internal/spx3"
    - "cl/internal/test"
    - "parser/fsx"
    - "x/jsonrpc2"
    - "x/watcher"
    - "x/langserver"
    - "x/fsnotify"
    - "x/fakenet"
    - "x/typesutil"
    - "x/gocmd"
    - "."
  