name: Format Check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: Check formatting
        run: |
          if [ -n "$(go fmt ./... | grep -v gop_autogen)" ]; then
            echo "Some files are not properly formatted. Please run 'go fmt ./...'"
            exit 1
          fi
          cd cmd/xgo; gop fmt -t ./...
